//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YP9.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class List_of_entries
    {
        public int ID { get; set; }
        public System.DateTime RecordingDate { get; set; }
        public int IDClientList { get; set; }
        public int IDListOfDoctors { get; set; }
        public string Cabinet { get; set; }
    
        public virtual Client_list Client_list { get; set; }
        public virtual List_of_doctors List_of_doctors { get; set; }
    }
}
