//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YP9.ApplicationData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hospitalEntities : DbContext
    {
        private static hospitalEntities _context;
        public hospitalEntities()
            : base("name=hospitalEntities")
        {
        }
        public static hospitalEntities GetContext()
        {
            if (_context == null)
                _context = new hospitalEntities();
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client_list> Client_list { get; set; }
        public virtual DbSet<List_of_doctors> List_of_doctors { get; set; }
        public virtual DbSet<List_of_entries> List_of_entries { get; set; }
    }
}
